[workspace]
members = [
	"node",
	"runtime",
	"frame/balances",
	"frame/timestamp",
	"frame/balances/rpc",
	"frame/balances/rpc/runtime-api",
	"client/consensus/manual-seal",
]
exclude = [
	"contracts",
]

[profile.release]
panic = "unwind"
